DROP TABLE IF EXISTS citylocation;

CREATE TABLE IF NOT EXISTS
citylocation(
  id SERIAL PRIMARY KEY NOT NULL,
  c_name VARCHAR(256) NOT NULL UNIQUE,
  display_name VARCHAR(256) NOT NULL UNIQUE,
  lat VARCHAR(256) NOT NULL,
  lon VARCHAR(256) NOT NULL
);